// src/app/layout

import type { Metadata } from 'next';
import '../styles/style.css';
import '../styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from '@/context/AuthContext'; // Import the AuthProvider
import { AuthWrapper } from '@/context/AuthWrapper';
import PageTransition from '@/components/page-ui/PageTransition';
import { Poppins } from 'next/font/google';
import Sidebar from '@/components/page-ui/sidebar';
import Header from '@/components/page-ui/header';
import { CartProvider } from '@/context/CartContext';

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Hey Jinnie',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico', // Path to your favicon in the `public` directory
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased`}>
        <AuthProvider>
          <ToastContainer position="top-center" />
          <AuthWrapper>
            <div className="layout-container">
              <CartProvider>
                {/* Persistent Sidebar */}
                <Sidebar />
                <div className="content-wrapper">
                  {/* Persistent Header */}
                  <Header />
                  <PageTransition>{children}</PageTransition>
                </div>
              </CartProvider>
            </div>
          </AuthWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
